# Site
repository: altis5526/personal-page
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chi-Yu Chen
title: Medical student
email: altis5526@gmail.com
website: https://altis5526.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  altis5526
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: tommy.chen.7165331
# flickr_username: jekyll
instagram_username: tommya5526
linkedin_username: chi-yu-chen-10a149221
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Chi-Yu, Chen, currently a <b>fifth grade medical student with a minor in computer science</b> in <b>National Yang Ming Chiao Tung University, Taiwan</b>. 
  My research interest includes <b>explainable AI model</b>, <b>computer vision</b>, and <b>smart medicine</b>.

  Programming skills:
  <b>C/C++</b>, <b>Python (PyTorch, OpenCV)</b>, <b>Web Programming</b>, iiiiiiiiiiiiiii

# content:
#   - title: Awards
#     layout: list
#     content:
#       - layout: top-middle
#         description: | 
#         Award 1

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: National Yang Ming Chiao Tung University
        # link_text: Project Website
        sub_title: Department of Medicine, minoring in computer science
        caption: September 2016 - Present
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research intern
        # link_text: boringcompany.com
#         sub_title: Multimedia Information System Lab (National Tsing Hua University)
#         caption: September 2021 - Present
        description: |
          - Multimedia Information System Lab, National Tsing Hua University (September 2021 - Present)
          - Neural Circuits and Cognition Lab, National Yang Ming Chiao Tung University (July 2019 - August 2019)
          - Lab of Tzyh-Chang Hwang, University of Missouri (July 2018 - August 2018)
          - Lab of Yeou-Guang Tsay, National Yang Ming Chiao Tung University (July 2017 - August 2017)
            
  - title: Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: First Place
        caption: 2022
        description: | # this will include new lines to allow paragraphs
          AI CUP 2022 MOE AI competition and labeled data acquisition project - Lung Adenocarcinoma Pathological Section Images: Tumor Airway Spread Detection Competition 1
      - layout: left
        title: First Place
        caption: 2022
        description: |
          IEEE International Conference on Digital Health (ICDH) Student Competition

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
